---
title: "Reading"
date: 2026-02-13
format: html
editor: visual
---

As an undergraduate student at The Ohio State University, I had the privilege of working with Dr. Ted Clark, Professor of Teaching, to research the intersectionality between chemical education and artificial intelligence (AI) in a classroom setting. My work with Dr. Clark ultimately led to two presentations through the American Association of Colleges and Universities (AAC&U) at Kenyon University and Otterbein University, as well as, a publication in the Journal of Chemical Education. Following this publication, I have remained interested in how to best convey difficult topics, particularly science, to college students. I want to convey material in an engaging and digestable way.

\
Reading Jeff Leek's "How to Be a Modern Scientist" provided ideas for effectively conveying material as an educator and instructor at an institutional level. Leek provided excellent tools in presenting strong lecture notes, videos, and code. Additionally, he provided tools for sharing MOOCs, as well. Before reading his work, I did not know what MOOCs were, but after discovering it, I have learned that it is a web-based educational platform, used in offering open-access courses. I think this is a useful tool for students in keeping accessibility at the forefront in digesting difficult material. Additionally, Leek reminds instructors to keep things short. I think this is incredibly important and is something that I have seen in my research as well. Leek writes, "... attention spans on the internet are very short" (Leek 51). It is best to keep things short and simple to keep students engaged.

\
In Leek’s work, I also learned about data sharing: how to best post, organize, and document your data. Data is a fast-paced, and ever-changing field. It is no longer constrained to use only in publications, presentations, and conferences; instead, it lives on blogs, websites, and social media. It’s growing prevalence is exactly the argument that Leek makes in his book - it is through these formats that data analysis, learning, and collaboration accelerate, rather than waiting until your work is finished and “perfect” before it is visible. A modern scientist must be adaptable and proactive. Tools of science, including online teaching, collaborative blogs, and interactive platforms, and implementing the thinking of a modern scientist means recognizing that science is a shared and evolving field.
